CREATE TABLE PLAYER(
	PLAYER_ID SERIAL NOT NULL,
	PLAYER_USERNAME VARCHAR(50) UNIQUE NOT NULL,
	PLAYER_EMAIL VARCHAR (50) UNIQUE NOT NULL,
	PLAYER_PASSWORD VARCHAR(50) NOT NULL,
	
	CONSTRAINT PK_PLAYER PRIMARY KEY (PLAYER_ID)
);
