CREATE TABLE PLAYER(
	PLAYER_ID SERIAL NOT NULL,
	PLAYER_USERNAME VARCHAR(50) UNIQUE NOT NULL,
	PLAYER_EMAIL VARCHAR (50) UNIQUE NOT NULL,
	PLAYER_PASSWORD VARCHAR(50) NOT NULL,
	
	CONSTRAINT PK_PLAYER PRIMARY KEY (PLAYER_ID)
);

CREATE TABLE PUZZLE(
	PUZZLE_ID BIGSERIAL NOT NULL,
	PUZZLE_LINES INT NOT NULL,
	PUZZLE_COLUMNS INT NOT NULL,
    PUZZLE_TYPE_SHUFFLE VARCHAR(255) NOT NULL,
	PUZZLE_URL_IMAGE VARCHAR(255) NOT NULL,
	CONSTRAINT PK_PUZZLE PRIMARY KEY (PUZZLE_ID)
);

CREATE TABLE PIECE(
	PUZZLE_ID BIGSERIAL NOT NULL,
    PIECE_INDEX INT NOT NULL,
    PIECE_CURRENT_POSITION INT NOT NULL,
	PIECE_EMPTY BOOLEAN NOT NULL,
	CONSTRAINT FK_PIECE FOREIGN KEY(PUZZLE_ID) 
	  REFERENCES PUZZLE(PUZZLE_ID)
)